'''
This is how you would find the multiples of a number
'''

# total_sum = 0
# for counter in range(1000):
#     if (counter%3 == 0 or counter%5 ==0):
#         total_sum = total_sum + counter
# print(total_sum)

'''
Fibonacci sequence is generated by adding the previous two numbers together.
By considering the terms in the fibonacci sequence whose values don't exceed 
four million, find the sum of the even-valued terms. 
'''

